<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TVMSPRMSPERFDB" failures="0" tests="9" name="Core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" time="0.191" errors="2" timestamp="2025-04-22T15:54:05 IST" skipped="7">
  <testcase classname="Core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="takeScreenshotOnFailure" time="0.172">
    <error message="Cannot invoke &quot;org.openqa.selenium.TakesScreenshot.getScreenshotAs(org.openqa.selenium.OutputType)&quot; because &quot;screenshot&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.TakesScreenshot.getScreenshotAs(org.openqa.selenium.OutputType)" because "screenshot" is null
at com.Utility.ScreenShot.takeScreenShot(ScreenShot.java:29)
at Core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass.takeScreenshotOnFailure(AlertsPlaceholderManagement_TestClass.java:252)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:677)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:661)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- takeScreenshotOnFailure -->
  <system-out/>
  <testcase classname="Core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Insert_New_Entry_All_Valid_Fields" time="0.000">
    <skipped/>
  </testcase> <!-- Insert_New_Entry_All_Valid_Fields -->
  <system-out/>
  <testcase classname="Core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Successful_Login" time="0.000">
    <skipped/>
  </testcase> <!-- Successful_Login -->
  <system-out/>
  <testcase classname="Core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Access_Alerts_and_Notifications" time="0.019">
    <error message="Input must be set" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Input must be set
at org.openqa.selenium.internal.Require.nonNull(Require.java:60)
at org.openqa.selenium.support.ui.FluentWait.<init>(FluentWait.java:94)
at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:74)
at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:43)
at Core.AlertsandNotifications.AlertsPlaceholderManagement_MainClass.clickOnAlertsAndNotifications(AlertsPlaceholderManagement_MainClass.java:63)
at Core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass.Access_Alerts_and_Notifications(AlertsPlaceholderManagement_TestClass.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- Access_Alerts_and_Notifications -->
  <system-out/>
  <testcase classname="Core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Access_Placeholder_Management" time="0.000">
    <skipped/>
  </testcase> <!-- Access_Placeholder_Management -->
  <system-out/>
  <testcase classname="Core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Pagination_Controls_Display" time="0.000">
    <skipped/>
  </testcase> <!-- Pagination_Controls_Display -->
  <system-out/>
  <testcase classname="Core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Paginate_to_Next_Page" time="0.000">
    <skipped/>
  </testcase> <!-- Paginate_to_Next_Page -->
  <system-out/>
  <testcase classname="Core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Paginate_to_Previous_Page" time="0.000">
    <skipped/>
  </testcase> <!-- Paginate_to_Previous_Page -->
  <system-out/>
  <testcase classname="Core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass" name="Search_Placeholder" time="0.000">
    <skipped/>
  </testcase> <!-- Search_Placeholder -->
  <system-out/>
</testsuite> <!-- Core.AlertsandNotifications.AlertsPlaceholderManagement_TestClass -->
