<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SPMUMLAP-043" failures="0" tests="7" name="Core.CallCentre.CoreAllocationSummary_TestClass" time="29.460" errors="1" timestamp="2025-05-09T13:13:31 IST" skipped="6">
  <testcase classname="Core.CallCentre.CoreAllocationSummary_TestClass" name="SetUp" time="29.460">
    <error message="Cannot invoke &quot;java.sql.Connection.prepareStatement(String)&quot; because &quot;con&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because "con" is null
at com.BasePackage.DBUtils.fetchSingleValueFromDB(DBUtils.java:22)
at com.BasePackage.Login_Class.CoreLogin(Login_Class.java:59)
at Core.CallCentre.CoreAllocationSummary_TestClass.SetUp(CoreAllocationSummary_TestClass.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:358)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- SetUp -->
  <testcase classname="Core.CallCentre.CoreAllocationSummary_TestClass" name="Validate_CallcentreSideMenu_Visibility" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_CallcentreSideMenu_Visibility -->
  <testcase classname="Core.CallCentre.CoreAllocationSummary_TestClass" name="Validate_AllocationSummaryPage_Displayed" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_AllocationSummaryPage_Displayed -->
  <testcase classname="Core.CallCentre.CoreAllocationSummary_TestClass" name="Validate_CallCentre_And_SearchButton_Are_Visible" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_CallCentre_And_SearchButton_Are_Visible -->
  <testcase classname="Core.CallCentre.CoreAllocationSummary_TestClass" name="Validate_WarningMessage_WithoutCallCentreDropdown" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_WarningMessage_WithoutCallCentreDropdown -->
  <testcase classname="Core.CallCentre.CoreAllocationSummary_TestClass" name="Validate_AllocationSummary_AccountDetails" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_AllocationSummary_AccountDetails -->
  <testcase classname="Core.CallCentre.CoreAllocationSummary_TestClass" name="Validate_Downloaded_ExcelData" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_Downloaded_ExcelData -->
</testsuite> <!-- Core.CallCentre.CoreAllocationSummary_TestClass -->
